name: size-shared-model
on: pull_request
      paths:
        - "shared-models/**"
        - ".github/workflows/size-shared-model.yaml"
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
